# import xlrd
# wb=xlrd.open_workbook('/home/zahoor-only/coding/python/100-days-python/day-7/BSCS.xlsx')
# ws=wb.sheet_by_index(0)
# for i in range(ws.nrows):
#     for j in range(ws.ncols):
#  print(ws.cell_value(i,j), end='\t')
#     print('')

names = ["NISHA SHARIF","MUHAMMAD ARSLAN","ELSA","TANZILA","MUHAMMAD ARFAN","MUZAMMIL HUSSAIN","ZAHOOR AHMAD","NOOR FATIMA","NATASHA ANWAR","MUHAMMAD ARHAM MURTAZA","ZARNAB NADEEM","MUHAMMAD JAWAD","MUHAMMAD ABUZAR","ALI ABBAS","BUSHRA SHAFIQUE","ASIF DANYAL","MUHAMMAD FAIZAN","KALSOOM TAHIR","SHAHZMAN MAZHAR","MUHAMMAD TALHA","KHADIJA","HURAIRA AHMAD ZAHID","ABDUL RAZZAQ","ZARQA NAWAZ","MUHAMMAD SAAD BIN KHALID","HASSAN MUKHTAR","SHERAZ AHMAD","MUHAMMAD UMAR SHEHZAD","DANISH IJAZ","ZOHA ASGHAR","SYED MUHAMMAD ZAEEM FAROOQ","KASHAF NOOR","MUHAMMAD AHMAD","MUHAMMAD IMRAN","HAMZA MUSHARAF","NOOR FATIMA","MUHAMMAD ILYAS CHISHTI","VANEEZA NOOR","HASSAN MANZOOR","YUSRA SAJJAD","SOHAIB KHAWER","USWAH IHSAN KHAN","MUHAMMAD SHERAZ","SAHIL JAHAN","BUSHRA FATIMA","FAKHAR ABBAS","UMAR ANAYAT","WAQAR AKRAM BHUTTA","SHAHZAIB ALI","AHMAD SABOOR","MOAZZAM ABBAS","ZAFAR IQBAL","ASAD DILAWAR","AHMAD NAZIR","AHSAN ALI","LAIBA KHAWAR","AMNA","NOOR UL HUDA","MUHAMMAD UMAR","MUHAMMAD HARIS ABBAS","AREEBA","ZAIN-UL-ABIDEN","IQRA ZAFAR RAO","ABDULLAH BIN TAHIR"]
